### ISSUE TITLE
Panorama registration has to be compliant with standard

### ISSUE THREAD

**Issue by ghost** [romainx/panorama#1]
Hi!

I am pasting the error I get when I try to use the command pelican content:

$ pelican content/
Traceback (most recent call last):
  File "/usr/bin/pelican", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/pelican/**init**.py", line 386, in main
    pelican, settings = get_instance(args)
  File "/usr/lib/python3.5/site-packages/pelican/**init**.py", line 380, in get_instance
    return cls(settings), settings
  File "/usr/lib/python3.5/site-packages/pelican/**init**.py", line 57, in **init**
    self.init_plugins()
  File "/usr/lib/python3.5/site-packages/pelican/**init**.py", line 84, in init_plugins
    plugin.register()
AttributeError: module 'panorama' has no attribute 'register'

How can I fix it?

**Comment by romainx** [comment]
Hello,

I will try to hel you. Could you give me some information about your configuration ?

The pelican version you are using:

```
pelican --version
```

The part of your `pelicanconf.py` configuration file referencing the module. For example:

```
PLUGIN_PATHS = ['../panorama']
PLUGINS = ['panorama']
```

Thanks

**Comment by ghost** [comment]
Hi, thank you for your help!

I will copy and paste my pelican version:
$ pelican --version
3.6.3

And part of my pelicanconf.py:

#!/usr/bin/env python

# -_\- coding: utf-8 -_-

from **future** import unicode_literals

THEME = 'themes/pelican-material-master/'
PATH = 'content'
PLUGIN_PATHS = ['plugins/']
PLUGINS = ['pelican-materialbox-master','pelican_youtube','share_post','liquid_tags','render_math',]

**Comment by ghost** [comment]
Hi again, this is the right part of my pelicancong:

PLUGIN_PATHS = ['plugins/']
PLUGINS = ['pelican-materialbox-master','pelican_youtube','share_post','liquid_tags','render_math','panorama']

**Comment by romainx** [comment]
OK sorry for my late answer.
The problem comes from the panorama plugin structure: it is defined in a panorama package and this is not the best way to do that.
I will fix it this week-end.

In the mean time a workaround is to declare the panorama path in the `PLUGIN_PATHS`:

```
PLUGIN_PATHS = ['plugins/','plugins/panorama']
```

I think it will work after that.
Sorry for the inconvenience.

**Comment by ghost** [comment]
It is so easy to fix... thank you!

I really love this plugin.

**Comment by romainx** [comment]
Thanks for the feedback I really appreciate.
I will work to improve it.
Could you give me the URL of your blog? I’m curious.

**Comment by ghost** [comment]
Hi !
This is the url of my stats:

http://lugarparaler.com/stats.html

I am still trying to make it show the graphics... but I feel that I am almost there...

**Comment by ghost** [comment]
Hi again!

This what I wrote in the stats.html before Pelican build it:

``` python
{% extends 'base.html' %}
{% block head %}
{{ super() }}
<link href="{{ SITEURL }}/{{ THEME_STATIC_DIR }}/panorama/nvd3/src/nv.d3.css" rel="stylesheet"/>
<script src="{{ SITEURL }}/{{ THEME_STATIC_DIR }}/panorama/d3/d3.min.js"></script>
<script src="{{ SITEURL }}/{{ THEME_STATIC_DIR }}/panorama/nvd3/nv.d3.min.js"></script>
{% endblock %}

{% block content %}
<section id="content">
    <header>
        <h1 class="entry-title">Estatísticas</h1>
    </header>
    <div class="entry-content">
            {% for chart in panorama_charts.values() %}
                <h2>{{ chart.name }}</h2>
                {{ chart.container }}
                {{ chart.htmlcontent }}
            {% endfor %}
    </div>
</section>
{% endblock %}
```

**Comment by ghost** [comment]
Is my stats.html ok?

Do I need to add something more? O change something?
Thank you!

**Comment by romainx** [comment]
I will study your case in more detail and write an answer.
In the mean time, here is the source of my blog: [aubonroman](https://github.com/romainx/romainx.github.com) where you can find the `pelicanconf.py`.

And here is the theme I use [pelican-subtle](https://github.com/romainx/pelican-subtle), where you can find the `stats.html` file.

Without analysis I guess the problem may come from this setting of the `pelicanconf.py`.

```
# Define stats template
DIRECT_TEMPLATES = (('index', 'tags', 'categories', 'authors', 'archives', 'stats'))
```

I will create an issue to make the integration easier since at this time it's a bit complicated.

**Comment by ghost** [comment]
Maybe the problem is the number of my posts: untill now, I only wrote 2 articles. Maybe the plugin work fine when I have more posts.
Well, thank you for your help !

**Comment by romainx** [comment]
I just saw on your blog that the plugin is working, great.

Here is an example of a `stats.html` using the default charts.

```
{% block content %}
<article>
  <div class="article_title">
    <h1><a href="{{ SITEURL }}/stats.html" class="nohover">Stats</a></h1>
  </div>
  <div class="article_text">
        <h2>Year</h2>
        {{ panorama_charts['nb_article_by_year'].container }}
        {{ panorama_charts['nb_article_by_year'].htmlcontent }}
        <h2>Month</h2>
        {{ panorama_charts['nb_article_by_month'].container }}
        {{ panorama_charts['nb_article_by_month'].htmlcontent }}
        <h2>Category</h2>
        {{ panorama_charts['nb_article_by_category'].container }}
        {{ panorama_charts['nb_article_by_category'].htmlcontent }}
        <h2>Category / Year</h2>
        {{ panorama_charts['nb_article_by_category_year'].container }}
        {{ panorama_charts['nb_article_by_category_year'].htmlcontent }}
  </div>
</article>
{% endblock %}
```

**Comment by ghost** [comment]
Hi!

Thank you so much!
